@echo off

if not exist Project\Android mkdir Project\Android
cd Project\Android

set C_ANDROID_TOOLCHAIN=%ANDROID_NDK%\build\cmake\android.toolchain.cmake
set C_ANDROID_NDK=%ANDROID_NDK%
set C_ANDROID_ABI=arm64-v8a
set C_ANDROID_PLATFORM=android-26
set C_BUILD_TUPE=Debug

cmake -DCMAKE_TOOLCHAIN_FILE=%C_ANDROID_TOOLCHAIN% -DANDROID_NDK=%C_ANDROID_NDK% -DANDROID_ABI=%C_ANDROID_ABI% -DANDROID_PLATFORM=%C_ANDROID_PLATFORM% -DCOMPILER_CLANG=ON -DTARGET_ANDROID=ON -DCMAKE_MAKE_PROGRAM=Ninja -GNinja -DCMAKE_BUILD_TYPE=%C_BUILD_TUPE% -DCRC32C_BUILD_TESTS=OFF -DCRC32C_BUILD_BENCHMARKS=OFF -DCRC32C_USE_GLOG=OFF -DCRC32C_INSTALL=OFF -DASSIMP_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DASSIMP_BUILD_ASSIMP_TOOLS=OFF ../..
cmake --build .

pause