@echo off
set VS_VERSION="Visual Studio 15 2017 Win64"

if not exist Project\Win64 mkdir Project\Win64
cd Project\Win64
cmake -DCOMPILER_MSVC=ON -G%VS_VERSION% -DCRC32C_BUILD_TESTS=OFF -DCRC32C_BUILD_BENCHMARKS=OFF -DCRC32C_USE_GLOG=OFF -DCRC32C_INSTALL=OFF -DASSIMP_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DASSIMP_BUILD_ASSIMP_TOOLS=OFF ../..

pause